name: Universal Mod Core CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                ref=`echo ${github_ref} | sed -e 's,refs/heads/,,' | tr '/' '-'`
                echo $ref
                echo "::set-env name=ref::$ref"
              env:
                github_ref: ${{ github.ref }}
                ACTIONS_ALLOW_UNSECURE_COMMANDS: true
            - name: XVFB
              run: sudo apt-get install -y xvfb findutils
            - name: Run Data
              run: xvfb-run --auto-servernum ./gradlew runData
            - name: Gradle build
              run: ./gradlew build
            - uses: actions/upload-artifact@v2-preview
              with:
                name: UniversalModCore-${{ env.ref }}
                path: build/libs/UniversalModCore-*.jar


